context:
  version: "1.27.0"

package:
  name: openmodelica
  version: ${{ version }}

source:
  url: https://github.com/OpenModelica/OpenModelica/releases/download/v${{ version }}/OpenModelica-v${{ version }}-src-with-submodules.zip
  sha256: 8bb23c0ae3dc1e8b2eed84f2ee24b0014ba837015a9230a5e0237d6789071bff
  patches:
    # drop erroneous _GNU_SOURCE define (error seems specific to conda-forge)
    - fmilib-gnusource.patch
    # Add OM_USE_SYSTEM_ZLIB option to fix stdio.h:210:7: error: expected identifier or '(' (updated to zlib 1.3.2 upstream)
    - zlib.patch
    # add macos/aarch64 platforms (https://github.com/robbr48/fmi4c/pull/97)
    - fmi4c.patch

build:
  number: 0
  skip:
    - win

requirements:
  build:
    - cmake
    - ninja
    - ${{ stdlib('c') }}
    - ${{ compiler('c') }}
    - ${{ compiler('cxx') }}
    - ${{ compiler('fortran') }}
    - if: unix
      then:
        - pkg-config
        - autoconf
        - automake
        - make
  host:
    - openjdk
    - libblas
    - liblapack
    - libcurl
    - libboost-devel
    - libffi
    - libiconv
    - qt-webengine
    - openscenegraph
    - if: linux
      then:
        - libgl-devel
        - libegl-devel
  run:
    - openjdk
    - cmake
    - make
    - zip
    - ${{ stdlib('c') }}
    - ${{ compiler('c') }}
    - ${{ compiler('cxx') }}
  run_constraints:
    - omcompiler <0

tests:
  - script:
      - omc --version
      - OMEdit --help
      - OMSimulator --help
      - echo 'loadFile("OMCompiler/Examples/Circle.mo"); getErrorString(); buildModelFMU(Circle); getErrorString();' > export.mos
      - omc export.mos
      - ls Circle.fmu
      - OMSimulator Circle.fmu
      - echo 'loadFile("OMCompiler/Examples/Circle.mo"); getErrorString(); buildModelFMU(Circle, platforms={"dynamic"}); getErrorString();' > export.mos
      - omc --fmuCMakeBuild=true --fmuRuntimeDepends=modelica export.mos
      - ls Circle.fmu
      - OMSimulator Circle.fmu
    files:
      source:
        - OMCompiler/Examples/Circle.mo

about:
  homepage: https://openmodelica.org/
  license: LicenseRef-OSMC-PL
  license_family: GPL
  license_file:
    - OSMC-License.txt
    - OMCompiler/3rdParty/antlr/3.2/libantlr3c-3.2/COPYING
    - OMCompiler/3rdParty/Cdaskr/LICENSE
    - OMCompiler/3rdParty/CMinpack/CopyrightMINPACK.txt
    - OMCompiler/3rdParty/gc/README.md
    - OMCompiler/3rdParty/FMIL/LICENSE.md
    - OMCompiler/3rdParty/libffi/LICENSE
    - OMCompiler/3rdParty/libzmq/COPYING.LESSER
    - OMCompiler/3rdParty/lis-1.4.12/COPYING
    - OMCompiler/3rdParty/metis-5.1.0/LICENSE.txt
    - OMCompiler/3rdParty/moo-0.1.0/COPYING.LESSER
    - OMCompiler/3rdParty/open62541/open62541.txt
    - OMCompiler/3rdParty/primme-3.2.3/COPYING.txt
    - OMCompiler/3rdParty/ryu/LICENSE-Apache2
    - OMCompiler/3rdParty/SuiteSparse-5.8.1/LICENSE.txt
    - OMCompiler/3rdParty/sundials-5.4.0/LICENSE
    - OMCompiler/3rdParty/tbb/LICENSE
    - OMCompiler/3rdParty/zlib/LICENSE
  summary: The Open Source Modelica Suite

extra:
  recipe-maintainers:
    - jschueller
